services:
  frontend:
    build: ./my-react-app
    container_name: frontend_c
    ports:
      - "3000:80"

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/devops
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_c
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: