services:
  frontend:
    image: ${DOCKERHUB_REPO_FRONTEND:-eg244991/event-planner-frontend}:${IMAGE_TAG:-latest}
    container_name: frontend_c
    ports:
      - "3000:80"

  backend:
    image: ${DOCKERHUB_REPO_BACKEND:-eg244991/event-planner-backend}:${IMAGE_TAG:-latest}
    container_name: backend_c
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/devops}
      - JWT_SECRET=${JWT_SECRET:-change-me}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_c
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
